---
title: "Digital Addiction"
subtitle: "My subtitle if needed"
author: 
  - Kenneth Chan, Stephanie Xuan Zhao, Siyu Li
thanks: "Code and data are available at: <https://github.com/YO7O/digital_addiction.git>"
date: today
date-format: long
abstract: "."
format: pdf
number-sections: true
#bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#install.packages("tidyverse")
#install.packages("haven")
#install.packages("readxl")
#install.packages("janitor")
#install.packages("ggpubr")

library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(ggpubr)

setwd("..")
#### Import Data ####
#### Explore ####
digital_clean_data <-
  read_csv(
   here::here("scripts/02_data_cleaning.R"),
    show_col_types = FALSE
  )

```

# Introduction
In 2023, there will be more than 4.95 billion users of different social media across the world. It has rapidly increased since 2015, as it only had 2.05 billion social media users at that time. (backlinko) According to Datareportal, in quarter 3 of 2021, it shows  46% of Americans spend 4 to 5 hours every day on their phones and 1 in 5 people have more than 4.5 hours per day of usage of their phone. With the development of technology, smartphones have started to offer more services and play a more important role in daily life. However, how the smartphone impacts our lives need more exploration for it. Based on this background, we will have discuss it from two aspects.  

Regarding our first argument, the article provides very valuable insights into the complexity of digital addiction and its impact on individuals and society, urging further research interventions to mitigate its negative effects. The authors discuss and analyze experiments related to subjective well-being. They administered four surveys to participants between April 12th and June 14th. Participants were randomized into rewarding and limiting treatment conditions using an analytic factor design. A participant-led experimental intervention known as the restriction group may have been a part of this. In order to evaluate the impacts of particular digital technology usage patterns on their well-being, experiments estimate treatment effects using regression models that include restriction and reward group indicators. These studies might compare the well-being levels of individuals who use various digital technologies, or they can monitor changes in participants' well-being before and after using digital technology. In research pertaining to mobile phone usage, control and restriction groups can be employed to evaluate the effects of interventions on cell phone use as well as the effects of cell phone use on an individual's behaviour or psychological state.

# Data
The authors in their experiment mainly adopted the standardized measures from the subjective well-being literature, where the respondents were required to answer the following seven questions of a questionnaire after conducting different groups of rules each week, Over the last three weeks," with a matrix of seven questions :

* "...I was a happy person." 
* "...I was satisfied with my I felt anxious." 
* "...I felt depressed." 
* "...I could concentrate on my life." 
* "...I could concentrate on what I was doing." 
* "...I was easily distracted." 
* "... I slept well." 

Based on the different responses it is possible to categorize and collect new data.


# Result
Figure 1
It shows dot plots that count the differences between two different groups in all directions of the survey, and explains the results of the control and treatment groups in the Subjective Well-Being of the survey. In this graph, the x-axis is the difference from the baseline, the y-axis is the subjective well-being, the orange line is the control group, the blue line is the treatment group, and the confidence interval is 95%. The treatment group was controlled by the researcher for the amount of time spent on Facebook per day and was rewarded accordingly for being controlled. The research target also generally responded that receiving the reward mechanism could greatly improve their subjective well-being. In contrast, there was not much change in the other survey directions. 
From the figure we can also see that the difference between the values of happiness, and conditions of life is excellent is not big, they are all concentrated in the range of -0.25 to 0.25. The subjective happiness of the treatment group will be a little bit lower than that of the control group at this time.


Figure 2
These two figures show the distribution of Facebook usage at Baseline and Endline. The red is the control group and the green is the treatment group. The Y-axis shows the fraction of the sample and the x-axis shows Facebook usage time.  For the longest time, the endline group’s time is shorter than the baseline’s time and the longest time both happen in the control group. The longest time for the treatment group is 550 minutes in baseline and 450 minutes in the endline group. For the treatment group, it decreases from 625 minutes to 575 minutes. To this result, there is a large decrease for the longest usage time. For the baseline, usage time exceeding 250 minutes is more than 2.5% in total but compared with it, at the endline, for the control group it has around 5% and for treatment is only 1.25%. 

It is obvious that between 0 and 125 minutes, the figure has a skew left and generally fraction decreases for each period in the treatment group. 


Figure 3
The above two figures show whether Facebook usage makes social life worse or better. The x-axis is formed from -6 to 6 which is based on a set of marking schemes for the research target to scale. From the figure, it has changed between -1 and 1. At baseline, it has the most fraction at 0 for the treatment group and in the control group, it has the most in -1 and 0. However, in endline’s figure, the biggest fraction shifts to the right. It becomes 0 and 1. This means that user feels their social life becomes better.


Figure 4

# Discuss

# Reference